NixOS/rfcs

- 0000-template.md
- README.md
> Implement RFC 0001

- rfcs/0004-replace-unicode-quotes.md
Nix uses unicode glyphs to quote strings and paths in its output. This RFC
proposes to use only ASCII `"` and `'` for quoting purposes in strings printed
during evaluation.
Rendered @ https://github.com/layus/rfcs/blob/master/rfcs/0004-replace-unicode-quotes.md
> [RFC 0004] Replace Unicode Quotes

- rfcs/0015-release-manager.md
Proposal on NixOS release managers by @fpletz and me.
Rendered: https://github.com/mayflower/nixos-rfcs/blob/release-manager/rfcs/0015-release-manager.md
cc @edolstra @domenkozar @rbvermaa @shlevy @grahamc
> [RFC 0015] NixOS Release Managers

- rfcs/0025-nix-core-team.md
Introducing the Nix Core Team.
[Rendered](https://github.com/grahamc/rfcs/blob/4fb9343dff52137cccd8e5b017181ac476d7b13b/rfcs/0025-nix-core-team.md).
Please register your approval or disapproval with the "Review Changes" feature. Obviously:
- Approval = Approval
- Request Changes = ... Not ... approval ...
and place any final feedback in the body of that review.
> [RFC 0025] Nix Core Team

- rfcs/0039-unprivileged-maintainer-teams.md
Package maintainers who are not able to commit directly to Nixpkgs
don't have adequate tools to attentively maintain their package.
OfBorg requests reviews of maintainers it can identify. GitHub only
allows requesting a review of a Collaborator of the repository.
This RFC bridges that gap, and allows OfBorg to request reviews of
maintainers.
Rendered: https://github.com/NixOS/rfcs/pull/39/files?short_path=68b0938#diff-68b0938e7e9a24cb0cc24ac6a70950b9
> RFC-0039: unprivileged maintainer team

- rfcs/0043-rfcsc-rotation.md
This is a draft RFC to implement rotation for the RFCSC.
cc @grahamc @NixOS/rfc-steering-committee @ciil
[Rendered Version](https://github.com/mayflower/nixos-rfcs/blob/rfcsc-rotation/rfcs/0043-rfcsc-rotation.md)
> [RFC 0043] RFC Steering Committee Rotation

- README.md
This reflects the fact that there is no "accepted" directory.
> "accepted" directory -> "rfcs" directory

- rfcs/0052-dynamic-ids.md
[summary]: #summary
A lot of NixOS modules are [assigning static uids/gids](https://github.com/NixOS/nixpkgs/blob/044cc701c23ede96355eb1dc997985b4dfac0372/nixos/modules/misc/ids.nix#L36) to their users. This has resulted in less than 90 static ids left in the reserved range from 0 to 400.
This RFC deprecates the practice of doing that and instead suggests to
- If applicable use systemd's `DynamicUser`
- Otherwise let NixOS assign dynamic persistent ids, which happens automatically when `users.users.<name?>.uid`/`users.groups.<name?>.gid` is not set. For users, `users.users.<name?>.isSystemUser` should be set so that only uids under 1000 are used by NixOS services.
Only in special circumstances are static ids allowed anymore.
[Rendered](https://github.com/Infinisil/rfcs/blob/dynamic-ids/rfc …
> [RFC 0052] Away from static IDs

- README.md
This paragraph seems to be a leftover or copy-pasta from the RFC template. It doesn't really fit into the flow of the text, so I think it was included or left here by mistake.
> README.md: remove template paragraph

- 0000-template.md
A few times I have asked people to separate examples from the core change we are deciding on, to have a terse, precise, and unambiguous normative bit that won't become more confusing when the context that makes something wordier flow is lost over time.
There is prior art for this sort of template revision:
In https://github.com/ghc-proposals/ghc-proposals/pull/251 it is pointed out that the combined section *both* be too wordy and have too few clarifying examples. This is a good point, lest this template change seem to skewed in favor of exports and against beginners: Everyone can win when we have terser detailed designs and far more examples. 
https://github.com/rust-lang/rfcs/pull/2059 is not an exact match, but I think is closer in spirit given th way things worked in practice. Before …
> Make the detailed design terse by separating examples

- rfcs/0046-platform-support-tiers.md
I hope to have some meta-discussion here so that #31 gets a language to discuss its specific merits.
[render link](https://github.com/7c6f434c/rfcs/blob/platform-support-tiers/rfcs/0046-platform-support-tiers.md)
> [RFC 0046] Platform Support Tiers

- rfcs/0055-retired-committers.md
Many people were given push access to the nixpkgs repository, which is kept even if these committers become inactive. This RFC proposes moving these contributors to a new team without push access.
[Rendered](https://github.com/tilpner/nixos-rfcs/blob/inactive/rfcs/0055-retired-committers.md)
> [RFC-0055] Retire inactive nixpkgs committers

- rfcs/0071-retired-committers-amendment.md
[Rendered](https://github.com/NixOS/rfcs/blob/2b9e71cdba74d4f377d5de34e1ffbc88e24c06fe/rfcs/0071-retired-committers-amendment.md)
> [RFC 0071] Retired Committers Amendment

- rfcs/0000-commonmark-docs.md
- rfcs/0072-commonmark-docs.md
This RFC proposes to convert the documentation for the Nix, Nixpkgs and NixOS projects from Docbook to CommonMark Markdown. It proposes requirements for the appearance of web facing documentation generated from Markdown. It does not mandate a choice of toolchain to generate a website with documentation. The choice is left to the implementers and maintainers.
[rendered](https://github.com/mboes/rfcs/blob/markdown-docs/rfcs/0000-commonmark-docs.md)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/rfcs/72)
> [RFC 0072] Switch to CommonMark for documentation

- rfcs/0032-run-phase-changes-for-better-nix-shell-use.md
Making some minor tweaks to how phases are run in the stdenv to improve the UX of nix-shell.
Rendered view: https://github.com/dezgeg/rfcs/blob/phase-changes/rfcs/0032-run-phase-changes-for-better-nix-shell-use.md
> [RFC 0032] Phase running changes for better nix-shell use

- rfcs/0080-nixos-release-schedule.md
This is meant to help minimize risk and work during the release stabilization period, by selecting a better time to branch-off from unstable.
Adapted from https://github.com/NixOS/rfcs/commit/8a3ba49393455fcf426488aef8b6d27d428c640c
Related discussions: 
- https://discourse.nixos.org/t/20-09-release-retrospective/9851
- https://discourse.nixos.org/t/what-should-stable-nixos-prioritize/9646
cc @worldofpeace @garbas @FRidh 
rendered: https://github.com/NixOS/rfcs/blob/ca06bb8dbb245f6a4c00311967e37753cd3d691a/rfcs/0080-nixos-release-schedule.md
> [RFC 0080] Change NixOS releases to YY.05,YY.11

- rfcs/0094-use-matrix-for-official-chat.md
[Rendered](https://github.com/ryantm/rfcs/blob/matrix/rfcs/0094-use-matrix-for-official-chat.md)
> [RFC 0094] Use Matrix for Official Chat

- rfcs/0046-platform-support-tiers.md
My intention was to add a link to the official platform list. However, I didn't manage to find one in the manual, so I only have a couple typo fixes so far.
[This file](https://github.com/NixOS/nixpkgs/blob/8377a7bca967dba811899164d4218d1d4a24b483/lib/systems/supported.nix) was referenced from the RFC #112 discussion. Is this authoritative enough to link to as the official reference?
> Rfc 46: Link platform list

- rfcs/0088-nixpkgs-breaking-change-policy.md
This specifies the expected workflow as a base for workflows and future automation.
[Rendered](https://github.com/kevincox/rfcs-1/blob/patch-1/rfcs/0088-nixpkgs-breaking-change-policy.md)
> [RFC 0088] Nixpkgs Breaking Change Policy

- rfcs/0106-nix-release-schedule.md
This RFC proposes doing new Nix releases every six weeks, as [previously proposed on Discourse](https://discourse.nixos.org/t/nix-release-schedule-and-roadmap/14204).
[Rendered](https://github.com/edolstra/rfcs/blob/nix-release-schedule/rfcs/0106-nix-release-schedule.md)
> [RFC 0106] Nix release schedule

- rfcs/0089-collect-non-source-package-meta.md
~Don't know if there's a way of reserving a number - I just picked `0088` as it looked like the latest.~
~Edit: oh - is it the PR number?~ Fixed.
See https://github.com/risicle/rfcs/blob/ris-from-source/rfcs/0089-collect-non-source-package-meta.md
> [RFC 0089] Collect non-source package meta attribute

- rfcs/0097-no-read-store-dir.md
This is effectively equal to `chmod o-r /nix/store`.
[Rendered](https://github.com/L-as/rfcs-1/blob/no-read-store-dir/rfcs/0097-no-read-store-dir.md)
> [RFC 0097] Unset read permission bit on /nix/store for other users

- rfcs/0102-moderation-team.md
The intention behind this RFC is to directly address the motivating problem behind #98 in a minimal way, building upon what seem to be the general points of agreement:
1) There is a desire to improve our ability to perform community moderation
1) Trust in the existing moderators
1) Agreement with the mission and statements of the NixOS Foundation
This RFC presumes that the team will take a few steps to self-organize, determine effective procedures, and communicate with the community writ-large - but purposefully leaves the specific details for the team to decide.
[Rendered](https://github.com/tomberek/rfcs/blob/0102/rfcs/0102-moderation-team.md)
Edit: through discussion, the oversight role of the Foundation has been replaced by the RFC process.
> [RFC 0102] Moderation Team

- rfcs/0119-testing-conventions.md
To better enable review software to run automatic testing, as well as help define when a PR is "tested enough"
rendered: https://github.com/jonringer/rfcs/blob/testing-rfc/rfcs/0119-testing-conventions.md
> [RFC 0119] Formalize testing for nixpkgs packages

- rfcs/0125-bootspec.md
Bootspec is a set of memoized facts about a system's closure.
These facts are used as the primary input for bootloader backends like
systemd-boot and grub, for creating files in `/boot/loader/entries/`
and `grub.cfg`.
In this proposal we create a stable, comprehensive, and machine-parsable
definition of a NixOS Generation as an intermediate representation (IR)
between the NixOS system definition and the bootloader management tools.
[rendered](https://github.com/grahamc/rfcs/blob/bootspec/rfcs/0125-bootspec.md)
(thanks @ryantm)
> [RFC 0125]: Use an intermediary representation (bootspec) for bootloader backends

- 0000-template.md
- README.md
Changes inspired by https://discourse.nixos.org/t/improving-our-rfc-process/28552/19. Changelog summary in the commit message. I took the opportunity to also update our template a bit.
I expect that these changes should be pretty uncontroversial and not require going through the formal RFC process, as they either clarify the intention in accordance with existing RFCs or make existing conventions explicit. In other words, nothing substantial should change with our process in practice.
There were more points discussed in the discourse thread that I did not manage to fit in: (~~The expectations around Shepherds and to which extent they may also be authors.~~ Edit: I don't think it should be mentioned in the RFC process currently, as there seems to be disagreement on some aspects of what …
> Update the RFC process documentation

- rfcs/0140-simple-package-paths.md
Auto-generate trivial top-level attribute definitions in Nixpkgs' `pkgs/top-level/all-packages.nix` from a Nixpkgs-internally standardised directory structure that matches the attribute name.
This makes it much easier to contribute new packages, since there's no more guessing needed as to where the package should go, both in the ad-hoc directory categories and in `pkgs/top-level/all-packages.nix`.
[Rendered](https://github.com/nixpkgs-architecture/rfcs/blob/master/rfcs/0140-simple-package-paths.md)
Implementation of part 1: https://github.com/NixOS/nixpkgs/pull/237439
Outdated implementation of part 2: https://github.com/NixOS/nixpkgs/pull/211832
This RFC has been worked on openly in [a repository](https://github.com/nixpkgs-architecture/simple-package-paths) by the new [Nixpkgs …
> [RFC 0140] Simple Package Paths

- rfcs/0136-stabilize-incrementally.md
This typo got added at the last minute while other mistakes were being corrected. See [1] and [2].
[1]: <https://github.com/NixOS/rfcs/pull/136#discussion_r1292537175>
[2]: <https://github.com/NixOS/rfcs/pull/136/commits/64fe8f30d9b75b78f6dd81359b14f5ac95abce93>
> [RFC 136] Fix typo

- rfcs/0145-doc-strings.md
What does a doc-comment look like?
The current Nix language doesn't offer doc comments. There is a vague convention that is not satisfying if you want to build reliable tooling.
Various previous PRs and issues tried of finding a solution to automatic API documentation of nix code. 
- https://github.com/NixOS/nix/pull/1652
- https://github.com/NixOS/nix/pull/5527
- https://github.com/NixOS/nix/issues/3904
(Are the most relevant i think)
I think https://github.com/NixOS/nix/pull/1652 is the best approach (yet) which also avoids runtime overhead. Unfortunately the maintainer of this PR couldn't manage to find a solution that satisfies all different opinions within the nix community, and thus it never got merged. I'd like to pick up the discussion on documentation again in this RFC format to …
> [RFC 0145] Doc-comments

- README.md
The RFC Steering Committee has started using an `RFCSC:` prefix to their messages posted on behalf of the committee to provide indication between personal opinion and communication from the committee. This updates the canned messages to include that prefix for consistency.
> Add `RFCSC:` prefix to canned messages.

- .gitattributes
This makes the project show up as being written in Markdown, which is common for these kinds of repos:
- https://github.com/swiftlang/swift-evolution/blob/main/.gitattributes
- https://github.com/Kotlin/KEEP/pull/332
- https://github.com/lit/rfcs/pull/40
> Make markdown detectable by linguist

- rfcs/0146-meta-categories.md
This RFC proposes a new `meta.categories` attribute in order to categorize Nix packages, instead of using the filesystem dirtree.
[Rendered!](https://github.com/AndersonTorres/rfcs/blob/meta-categories/rfcs/0146-meta-categories.md)
> [RFC 0146] Meta.Categories, not Filesystem Directory Trees

- .github/workflows/update-pr-labels.yml
Updates labels when an RFC gets merged:
`status: FCP` -> `status: accepted`
There might be more automation we want to do, this is just what seemed most obvious to me at the moment.
> ci: update labels on merged PRs

- rfcs/0032-run-phase-changes-for-better-nix-shell-use.md
- rfcs/0051-mark-stale-issues.md
- rfcs/0071-retired-committers-amendment.md
- rfcs/0080-nixos-release-schedule.md
- rfcs/0085-nixos-release-stablization.md
- rfcs/0088-nixpkgs-breaking-change-policy.md
- rfcs/0089-collect-non-source-package-meta.md
- rfcs/0092-plan-dynamism.md
- rfcs/0094-use-matrix-for-official-chat.md
- rfcs/0097-no-read-store-dir.md
- rfcs/0102-moderation-team.md
- rfcs/0106-nix-release-schedule.md
- rfcs/0108-nixos-containers.md
- rfcs/0119-testing-conventions.md
- rfcs/0124-nix-mark-stale-issues.md
- rfcs/0125-bootspec.md
- rfcs/0127-issues-warnings.md
- rfcs/0130-stalled-rfcs.md
- rfcs/0132-meson-builds-nix.md
- rfcs/0136-stabilize-incrementally.md
- rfcs/0145-doc-strings.md
- rfcs/0146-meta-categories.md
- YAML strings cannot start with `@` (affected 22 files)
- YAML strings cannot start with `[` (affected 2 files)
In both cases we can just double-quote the value to fix the problem.
> Fix invalid YAML formatting
